%% A_provagamba compila funzione mex
% IN(1) - directory of the .cpp file to compile
% IN(2) - name of the .cpp file to compile

function []=compileCPP()
clear mex;
function_dir=pwd;
function_name='Integrate_Runner_NEAT_vFAST.cpp';
opensim_dir = fullfile(pwd, '/../OpenSimInstall');
cpp_file=[function_dir,'\',function_name];

fprintf('Compiling MexfastID function ... \n');

mex(['-I',opensim_dir],...
    ['-I',opensim_dir,'\bin'],...
    ['-I',opensim_dir,'\sdk\include'],...
    ['-I',opensim_dir,'\sdk\include\SimTK\include'],...
    ['-I',opensim_dir,'\sdk\include\OpenSim\common'],...
    ['-L',fullfile(pwd, '/../OpenSimInstall/sdk/lib')],...
    '-llibblas',...
    '-lliblapack',...
    '-lSimTKcommon',...
    '-lSimTKmath',...
    '-lSimTKsimbody',...
    '-losimActuators',...
    '-losimAnalyses',...
    '-losimCommon',...
    '-losimLepton',...
    '-losimSimulation',...
    '-losimTools',...
    '-lpthreadVC2_x64',cpp_file);
