%% A_provagamba compila funzione mex
% IN(1) - directory of the .cpp file to compile
% IN(2) - name of the .cpp file to compile

function []=compilamex(varargin)
clear mex;
function_dir=varargin{1};
function_name=varargin{2};
if length(varargin)>2
    opensim_dir=varargin{3};
else
    opensim_dir = 'C:\Users\u0113530\Documents\AI RUNNING\OpenSimInstall';
end
cpp_file=[function_dir,'\',function_name];

fprintf('Compiling MexfastID function ... \n');

mex(['-I',opensim_dir],...
    ['-I',opensim_dir,'\bin'],...
    ['-I',opensim_dir,'\sdk\include'],...
    ['-I',opensim_dir,'\sdk\include\SimTK\include'],...
    ['-I',opensim_dir,'\sdk\include\OpenSim\common'],...
    ['-L','C:\Users\u0113530\Documents\AI RUNNING\OpenSimInstall\sdk\lib'],...
    '-llibblas',...
    '-lliblapack',...
    '-lSimTKcommon',...
    '-lSimTKmath',...
    '-lSimTKsimbody',...
    '-losimActuators',...
    '-losimAnalyses',...
    '-losimCommon',...
    '-losimLepton',...
    '-losimSimulation',...
    '-losimTools',...
    '-lpthreadVC2_x64',cpp_file);
